baseURL                          = "https://pnmcosta.github.io/"   # Your domain name. Must end with "/"
theme                            = "introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                     # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                     # https://gohugo.io/templates/internal/#google-analytics

[params]
    themeStyle                   = "auto"                  # Choose "light" or "dark" or "auto"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "pnmcosta@gmail.com"   # E-mail address for contact section
    customCSS                  = ["custom.css"]             # Include custom css files placed under assets/
    # customJS                   = ["foo.js"]              # Include custom JavaScript files placed under assets/
    # plausible                  = true                    # Use Plausible analytics (requires an account at Plausible.io)

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = false                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = false                    # show all posts in an archive format
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = false                    # Show your current local time in contact section
        timeZone                 = "America/Los_Angeles"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "en-US"                 # Language specific format to use
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        pinterest                = true

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "/Pedro-Maia-Costa.pdf"
        icon  = "user-circle" # icon name without the 'fa-'
        icon_pack = "fas"
        html_attributes = "title=\"Download Resume\" target=\"_blank\"" 
    [[params.social]]
        url   = "https://www.linkedin.com/in/pnmcosta/"
        icon  = "linkedin" # icon name without the 'fa-'
        icon_pack = "fab"
        html_attributes = "title=\"View my LinkedIn profile\" target=\"_blank\"" 
    [[params.social]]
        url   = "https://github.com/pnmcosta"
        icon  = "github" # icon name without the 'fa-'
        icon_pack = "fab"
        html_attributes = "title=\"View my GitHub profile\" target=\"_blank\"" 
    [[params.social]]
        url = "mailto:pnmcosta@gmail.com"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"
        html_attributes = "title=\"Email me\"" 


# If you don't want to use the default menu, you can define one by yourself
[[menu.main]]
     name    = "Home"
     url     = "/"
     weight  = 0
# [[menu.main]]
#     name    = "Blog"
#     url     = "/blog/"
#     weight  = 1

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"
  series = "series"

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content"
        weight           = 0
        title            = "Pedro Costa"
        [languages.en.params]
            description  = "The homepage of Pedro Costa, senior software engineer and architect. You&rsquo;ll find my resume, social links and projects."   # Max 160 characters show in search results
            footerText   = "Under construction, additional content brewing..."                      # Text to override default footer text (markdown allowed)