name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: 20.8.1
          cache: npm
          cache-dependency-path: |
            package-lock.json

      - run: npx tailwindcss -i ./src/input.css -o ./src/output.css

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src